### ISSUE TITLE
Can't compile in current Android Studio

### ISSUE THREAD

**Issue by xtrude64** [justinodwyer/Beacon-Scanner-and-Logger#10]
Is there a more current version of this?

I am going crazy just trying to get an app working from source code from 2014, and it is frustrating.

**Comment by justinodwyer** [comment]
Hi there,

Apologies for the delay getting back to you, can you share any detail on the specific issues you're having? The fact the source code is a few years old isn't necessarily an issue (the app works fine on Android M) I'm wondering if perhaps you're missing a dependency?

Cheers,
Justin
