### ISSUE TITLE
Why there are so many missing values?

### ISSUE THREAD

**Issue by chester256** [justinodwyer/Beacon-Scanner-and-Logger#12]
Hi Justin,
Thanks for your APP. It helps me a lot! However, recently I find that there are many missing values of the log data, which means some scanning intervals are larger than the interval I have set. Theoretically, what is the smallest scanning interval? Have you use any algorithms to denoise the RSSI? Thank you very much.

**Comment by justinodwyer** [comment]
Hi Chester,

Apologies for the delay in getting back to you, I'm using libraries from
the talented folks over at Radius Networks to do the actual detection, so
I'm afraid I can't provide much assistance with your query.

I know they release updated versions of the library though, and I think
these include profiles for newer devices, so you may want to build your own
version of the app after updating external dependencies - apologies if
you've already done this and I've misunderstood.

Hope this is in some way helpful, and I'm really glad to hear the app has
been of use.

All the best,
Justin
