### ISSUE TITLE
Tasker Support?

### ISSUE THREAD

**Issue by NoobTW** [justinodwyer/Beacon-Scanner-and-Logger#4]
Is it possible to make it support Tasker?

**Comment by justinodwyer** [comment]
Hi there,

I had a similar request a few months ago and produced a special build of the app that produces a temp file which Tasker can be configured to listen out for. When a beacon is detected it's written to the file and the file only contains one record at a time, which corresponds to the last beacon discovered. 

I'll find this "special" build and upload it, which should give you what you need until I produce the next production build of the app (due in the next few weeks, once I've added Eddystone support).

Watch this space, I'll provide a download link soon.

Cheers,
Justin

**Comment by justinodwyer** [comment]
Experminental Tasker support APK uploaded here (with readme file): https://github.com/justinodwyer/Beacon-Scanner-and-Logger/tree/master/custom%20builds/experimental%20Tasker%20support

Closing issue.
