### ISSUE TITLE
git clone exceptions 

### ISSUE THREAD

**Issue by peteanusergiu** [justinodwyer/Beacon-Scanner-and-Logger#9]
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xhdpi-v4/common_signin_btn_icon_disabled_focus_light.9.png (Filename too long)
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xhdpi-v4/common_signin_btn_text_disabled_focus_light.9.png (Filename too long)
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xxhdpi-v4/common_signin_btn_icon_disabled_focus_dark.9.png (Filename too long)
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xxhdpi-v4/common_signin_btn_icon_disabled_focus_light.9.png (Filename too long)
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xxhdpi-v4/common_signin_btn_text_disabled_focus_dark.9.png (Filename too long)
error: unable to create file AndroidStudio (v1_4 onwards)/IBeaconPoC/IBeaconPoC/build/intermediates/exploded-aar/IBeaconPoC/googleplayservices_lib/unspecifie
d/res/drawable-xxhdpi-v4/common_signin_btn_text_disabled_focus_light.9.png (Filename too long)
Your branch is up-to-date with 'origin/master'.

**Comment by justinodwyer** [comment]
Hi there, apologies for the delay responding on this. Are you still experiencing this issue, or is it now resolved for you?
